name: sheepy
version: '2.0.0'
main: me.nukmuk.sheepy.Sheepy
api-version: '1.21'
commands:
  sheepy:
    description: Sheepy main command
    usage: "/sh"
    aliases: [ sh ]
    permission: sheepy.use
  misc:
    permission: sheepy.misc
permissions:
  sheepy.use:
    default: op
  sheepy.misc:
    default: op
